.TH project1 "2021-12-28" "" project1 man 
 
.SH NAME
project1

.SH SYNOPSIS
.B 
[\fB\ ls\fR] list directory contents.
[\fB\ ls -a\fR] list all files including hidden files.
[\fB\ ls -1\fR] list all files in "long" format.
[\fB\ mkdir\fR] create new directory.
[\fB\ touch\fR] create new file.
[\fB\ rm\fR] delete the file.
[\fB\ rmdir\fR] delete the directory.
[\fB\ cp\fR] copy file from one location to another.
[\fB\ -\-help\fR] help and exit.
[\fB\ -\-version\fR] output version and exit.

.SH DESCRIPTION
.B project1
this project manages files and directories : (1) Listing information about files and directories including hidden files,(2) Creating new directories and files ,(3) Deleting files and directories , (4) Copying folder with its files to another folder.
.SH OPTIONS
.TP
.BR \ ls 
list all files or directories in the current directory by default.
.TP
.BR \ ls -a 
list all files including hidden files.
.TP
.BR \ ls -1
list all files in "long" format.
.TP
.BR \ mkdir
Create the directories, if they do not already exist.
.TP
.BR \ touch
create a new file.
.TP
.BR \ rm 
Remove each specified file.  By default, it does not remove directories.
.TP
.BR \ rmdir 
Remove a directory.
.TP
.BR \ cp
copy file from one location to another, it Copy source to dest, or multiple sources to directory.
.TP
.BR \ -\-help
display help and exit.
.TP
.BR \ -\-version
output version information and exit.
.SH AUTHOR
written by Nada Mohamed,Farah Tarek,Maryam Sherif,Karim Ragab,Antonious Awad.
